# Build and test solids4foam using Docker containers
name: Build and test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-on-openfoam-v2012:
    name: Build on OpenFOAM-v2012
    runs-on: ubuntu-latest
    container:
      image: philippic/openfoam-v2012-ubuntu20.04:latest
    steps:
      - uses: actions/checkout@v3

      - name: Allwmake
        shell: bash -l {0}
        run: |
          source /usr/lib/openfoam/openfoam2012/etc/bashrc
          ./Allwmake

      - name: Alltest
        shell: bash -l {0}
        run: |
          source /usr/lib/openfoam/openfoam2012/etc/bashrc
          cd tutorials
          ./Alltest
