# Build and test solids4foam using Docker containers
name: Build and test

on:
  push:
    branches: [ "nextRelease" ]
  pull_request:
    branches: [ "nextRelease" ]
  workflow_dispatch:

jobs:
  build-and-test-on-openfoam-v2012:
    name: Build on OpenFOAM-v2012
    runs-on: ubuntu-latest
    container:
      image: philippic/openfoam-v2012-ubuntu20.04:latest
    steps:
      - uses: actions/checkout@v3

      - name: Allwmake
        shell: bash -l {0}
        run: |
          source /usr/lib/openfoam/openfoam2012/etc/bashrc
          ./Allwmake

      - name: Alltest
        shell: bash -l {0}
        run: |
          source /usr/lib/openfoam/openfoam2012/etc/bashrc
          cd tutorials
          ./Alltest

  build-and-test-on-openfoam-9:
    name: Build on OpenFOAM-9
    runs-on: ubuntu-latest
    container:
      image: philippic/openfoam-9-ubuntu20.04:latest
    steps:
      - uses: actions/checkout@v3

      - name: Allwmake
        shell: bash -l {0}
        run: |
          source /opt/openfoam9/etc/bashrc
          ./Allwmake

      - name: Alltest
        shell: bash -l {0}
        run: |
          source /opt/openfoam9/etc/bashrc
          cd tutorials
          ./Alltest

  build-and-test-on-foamextend41:
    name: Build on foam-extend-4.1
    runs-on: ubuntu-latest
    container:
      image: philippic/foam-extend-4.1.ubuntu18.04.gfortran:latest
    steps:
      - uses: actions/checkout@v3

      - name: Allwmake
        shell: bash -l {0}
        run: |
          source /home/dockeruser/foam/foam-extend-4.1/etc/bashrc
          ./Allwmake

      - name: Alltest
        shell: bash -l {0}
        run: |
          source /home/dockeruser/foam/foam-extend-4.1/etc/bashrc
          cd tutorials
          ./Alltest