# Build and push solids4foam docker images to docker hub
name: Build and push docker images

on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]
    branches: [ "nextRelease" ]
  workflow_dispatch:

jobs:
  docker-openfoam-v2012:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the OpenFOAM-v2012 image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: solids4foam/solids4foam-v2.0-openfoam-v2012:latest
          file: Dockerfile.openfoamv2012

  docker-openfoam-9:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the OpenFOAM-9 image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: solids4foam/solids4foam-v2.0-openfoam-9:latest
          file: Dockerfile.openfoamv9

  docker-foam-extend-4.1:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the foam-extend-4.1 image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: solids4foam/solids4foam-v2.0-foam-extend-4.1:latest
          file: Dockerfile.foamextend41